### ISSUE TITLE
Downloading into Root Folder warning. Warnings won't go away.

### ISSUE THREAD

**Issue by Leesterpeester** [Servarr/Wiki#137]
Health message:
"Download client Sab places downloads in the root folder /Shares/Movies. You should not download to a root folder."

Not downloading to / and Not an actual health issue and I can't accept/ignore.  Bottom line this should not be a warning.

**Comment by bakerboy448** [comment]
This Servarr GitHub is not for support.

The healthcheck is accurate and based on both the root folders you have configured in Radarr and the download folder(s) reported by your download client.

downloading in your root folder absolutely should be a warning as it always causes problems.

every instance we have seen of this being triggered and users saying they are not...turns out they had their download folder added as a root folder.

Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for radarr support/questions.

**Comment by Leesterpeester** [comment]
Thanks Bakerboy488 My bad I didn't this was for the wiki only
