### ISSUE TITLE
Missing information in settings pages

### ISSUE THREAD

**Issue by EZ64cool** [Servarr/Wiki#211]
I was setting up a private tracker and wanted to set a seed ratio with an infinite timer.
Looking through the Wiki it wasn't 100% clear on how to do this, after looking through sonarr's implementation it looks like setting an indexers seed time to -1 will result in an infinite time, and -2 seems to result in the maximum possible seed time.

It would be nice to have this in the docs.

Thanks

**Comment by augustuen** [comment]
IMO this is already covered by [these points](https://wiki.servarr.com/radarr/settings#torrent-tracker-configuration):

* Seed Ratio - If empty, use the download client default. Otherwise, the minimum seed ratio required for your download client to meet for releases from this indexer prior to it being paused by your client and removed by Radarr (Requires Completed Download Handling - Remove enabled)
* Seed Time - If empty, use the download client default. Otherwise, the minimum seed time in minutes required for your download client to meet for releases from this indexer prior to it being paused by your client and removed by Radarr (Requires Completed Download Handling - Remove enabled)

Seed limits aren't required fields, and if you don't set it, the Arrs won't set limits for their torrents, instead letting your client handle it. Furthermore, it doesn't look like negative seed limits are supposed to accepted, but that would be bugs with the Arrs which need to be reported on their respective Githubs.

**Comment by EZ64cool** [comment]
For some reference, I'm using qBittorrent which does support negative values.
https://github.com/Sonarr/Sonarr/blob/ca8b26138e3ebd793cc1a5fd51522ce3eda8a2e1/src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs#L621

Looking at the other clients this doesn't seem to be the case for all of them.
Not sure if there is qBittorrent specific page that could explain this otherwise I guess it's findable through the source files.

**Comment by bakerboy448** [comment]
You may wish to check out qbit manage then which can handle seed goals and no hardlinks
